version: "3"
services:
  restreamer:
    image: datarhei/restreamer
    container_name: restreamer
    ports:
      - 1935:1935
      - 8080:8080
    networks:
      - frontend
    volumes:
      - "~/db:/restreamer/db"
    environment:
      - RS_USERNAME=admin
      - RS_PASSWORD=datarhei
      - RS_LOGLEVEL=4
      - RS_TIMEZONE=Europe/Berlin
      - RS_SNAPSHOT_INTERVAL=1m
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 10s

  fblive:
    image: dweomer/stunnel
    container_name: fblive
    expose:
      - 1936
    networks:
      - frontend
    restart: always
    environment:
      - STUNNEL_SERVICE=fb-live
      - STUNNEL_CLIENT=yes
      - STUNNEL_ACCEPT=1936
      - STUNNEL_CONNECT=live-api-s.facebook.com:443
      - STUNNEL_VERIFY_CHAIN=NO

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - frontend
    environment:
      DOMAINS: localhost -> http://restreamer:8080
      STAGE: local
      # DOMAINS: yourdomain.com -> http://restreamer:8080
      # STAGE: production

networks:
  frontend:
